# This file is generated by decompiling building.grf with grftopy.
# It's is only intended to be used as reference, don't expect it to actually run and produce grf.

import datetime
import grf
from grf import TRAIN, RV, SHIP, AIRCRAFT, STATION, CANAL, BRIDGE, HOUSE, GLOBAL_VAR, INDUSTRY_TILE, INDUSTRY, CARGO, SOUND_EFFECT, AIRPORT, SIGNAL, OBJECT, RAILTYPE, AIRPORT_TILE, ROADTYPE, TRAMTYPE, ROAD_STOP
from grf import ZOOM_NORMAL, ZOOM_4X, ZOOM_2X, ZOOM_OUT_2X, ZOOM_OUT_4X, ZOOM_OUT_8X
from grf import Ref, CB, ImageFile, FileSprite, WithMask, RAWSound, PaletteRemap

g = grf.BaseNewGRF()

# Bind all the used classes to current grf so they can be used declaratively
SetDescription, DefineMultiple, If, ComputeParameters, Action1, SetProperties, BasicSpriteLayout, Action3, RandomSwitch, Define = g.bind(grf.SetDescription), g.bind(grf.DefineMultiple), g.bind(grf.If), g.bind(grf.ComputeParameters), g.bind(grf.Action1), g.bind(grf.SetProperties), g.bind(grf.BasicSpriteLayout), g.bind(grf.Action3), g.bind(grf.RandomSwitch), g.bind(grf.Define)

# New container header: 00:00:47:52:46:82:0d:0a:1a:0a
# Offset: 2243 compresion: 0
# Magic sprite: 04:00:00:00:ff:02:00:00:00
# 1: Sprite(665, ff) <14>: 14:43:49:4e:46:4f:42:50:41:4c:53:01:00:44:54:4e:41:4d:45:7f:43:68:69:6e:61:20:53:65:74:3a:20:42:75:69:6c:64:69:6e:67:73:20:94:30:2e:31:2e:30:2d:49:4e:44:45:56:00:54:4e:41:4d:45:56:c3:9e:e4:b8:ad:e5:9b:bd:e5:8c:85:ef:bc:9a:e5:bb:ba:e7:ad:91:20:ee:82:94:30:2e:31:2e:30:00:54:44:45:53:43:7f:0d...
SetProperties(
    props={   b'INFO': {   b'PALS': [b'D'],
                           b'NAME': [   (127, b'China Set: Buildings \x940.1.0-INDEV'),
                                        (   86,
                                            b'\xc3\x9e\xe4\xb8\xad\xe5\x9b\xbd\xe5\x8c\x85\xef\xbc\x9a\xe5\xbb\xba\xe7\xad\x91'
                                            b' \xee\x82\x940.1.0')],
                           b'DESC': [   (   127,
                                            b'\r\x9a\x1f\x8aChina\x8b Set\x9a : Buildings \x9a\x1f\x940.1.0-INDEV\x9a \r\rInsert'
                                            b' your description here.\r\rDistributed under \x9a\x1f\x89GPL v2\x9a .'),
                                        (   86,
                                            b'\xc3\x9e\r\xee\x82\x9a\x1f\xee\x82\x8a\xe4\xb8\xad\xe5\x9b\xbd\xee\x82\x8b\xe5'
                                            b'\x8c\x85\xee\x82\x9a \xef\xbc\x9a\xe5\xbb\xba\xe7\xad\x91 - \xee\x82'
                                            b'\x9a\x1f\xee\x82\x940.1.0-INDEV\xee\x82\x9a \r\r\xe6\x9c\xac NewGRF \xe6\x98\xaf'
                                            b' Blablabla\xe3\x80\x82\r\r\xe5\x9c\xa8 \xee\x82\x9a\x1f\xee\x82\x89GPL v2'
                                            b'\xee\x82\x9a  \xe4\xb8\x8b\xe5\x88\x86\xe5\x8f\x91\xe3\x80\x82')],
                           b'BLTR': [b'3'],
                           b'VRSN': [b'\x00\x00\x00\x00'],
                           b'MINV': [b'\x00\x00\x00\x00'],
                           b'URL_': [(0, b'https://www.tt-forums.net/viewtopic.php?t=91092')],
                           b'NPAR': [b'\x01'],
                           b'PARA': {   b'\x00\x00\x00\x00': {   b'NAME': [   (127, b'Vanilla buildings'),
                                                                              (   86,
                                                                                  b'\xc3\x9e\xe5\x8e\x9f\xe7\x89\x88'
                                                                                  b'\xe5\xbb\xba\xe7\xad\x91')],
                                                                 b'DESC': [   (127, b'Whether to disable vanilla buildings'),
                                                                              (   86,
                                                                                  b'\xc3\x9e\xe6\x98\xaf\xe5\x90\xa6'
                                                                                  b'\xe4\xbf\x9d\xe7\x95\x99\xe5\x8e'
                                                                                  b'\x9f\xe7\x89\x88\xe5\xbb\xba\xe7\xad\x91')],
                                                                 b'TYPE': [b'\x00'],
                                                                 b'DFLT': [b'\x00\x00\x00\x00'],
                                                                 b'LIMI': [b'\x00\x00\x00\x00\x01\x00\x00\x00'],
                                                                 b'VALU': {   b'\x00\x00\x00\x00': [   (127, b'Disabled'),
                                                                                                       (   86,
                                                                                                           b'\xc3\x9e\xe4\xb8'
                                                                                                           b'\x8d\xe4\xbf\x9d'
                                                                                                           b'\xe7\x95\x99')],
                                                                              b'\x01\x00\x00\x00': [   (127, b'Enabled'),
                                                                                                       (   86,
                                                                                                           b'\xc3\x9e\xe4\xbf'
                                                                                                           b'\x9d\xe7\x95\x99')]}}}}}
)

# 2: Sprite(148, ff) <08>: 08:08:5f:5f:03:06:43:68:69:6e:61:20:53:65:74:3a:20:42:75:69:6c:64:69:6e:67:73:20:94:30:2e:31:2e:30:2d:49:4e:44:45:56:00:0d:9a:1f:8a:43:68:69:6e:61:8b:20:53:65:74:9a:20:3a:20:42:75:69:6c:64:69:6e:67:73:20:9a:1f:94:30:2e:31:2e:30:2d:49:4e:44:45:56:9a:20:0d:0d:49:6e:73:65:72:74:20:79:6f:75:72...
SetDescription(
    format_version=8,
    grfid=b'__\x03\x06',
    name=b'China Set: Buildings \x940.1.0-INDEV',
    description=b'\r\x9a\x1f\x8aChina\x8b Set\x9a : Buildings \x9a\x1f\x940.1.0-INDEV\x9a \r\rInsert your description here.\r\rDistributed under \x9a\x1f\x89GPL v2\x9a .',
)

# 3: Sprite(9, ff) <0d>: 0d:40:00:11:fe:ff:ff:00:00
# [40] = [11]
ComputeParameters(
    target=64,
    operation=0,
    if_undefined=False,
    source1=17,
    source2=254,
    value=None,
)

# 4: Sprite(9, ff) <09>: 09:00:04:02:01:00:00:00:01
If(
    is_static=True,
    variable=0,
    varsize=4,
    condition=2,
    value=1,  # \x01\x00\x00\x00
    skip=1,
)

# 5: Sprite(118, ff) <00>: 00:07:01:6e:ff:00:00:08:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff...
DefineMultiple(
    feature=HOUSE,
    first_id=0,
    count=110,
    props={'substitute': [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]}
)

# 6: Sprite(18, ff) <00>: 00:07:05:01:ff:81:00:13:1f:f8:0b:01:18:10:08:14:09:11
Define(
    feature=HOUSE,
    id=129,
    props={
        'availability_mask': 63519,
        'population': 1,
        'probability': 16,
        'substitute': 20,
        'flags': 17,
    }
)

# 7: Sprite(18, ff) <00>: 00:07:05:01:ff:82:00:13:00:00:0b:00:18:00:08:15:09:00
Define(
    feature=HOUSE,
    id=130,
    props={
        'availability_mask': 0,
        'population': 0,
        'probability': 0,
        'substitute': 21,
        'flags': 0,
    }
)

# 8: Sprite(18, ff) <00>: 00:07:05:01:ff:83:00:13:00:00:0b:00:18:00:08:16:09:00
Define(
    feature=HOUSE,
    id=131,
    props={
        'availability_mask': 0,
        'population': 0,
        'probability': 0,
        'substitute': 22,
        'flags': 0,
    }
)

# 9: Sprite(18, ff) <00>: 00:07:05:01:ff:84:00:13:00:00:0b:00:18:00:08:17:09:00
Define(
    feature=HOUSE,
    id=132,
    props={
        'availability_mask': 0,
        'population': 0,
        'probability': 0,
        'substitute': 23,
        'flags': 0,
    }
)

# 10: Sprite(6, ff) <01>: 01:07:20:ff:01:00
Action1(
    feature=HOUSE,
    set_count=32,
    sprite_count=1,
    first_set=None,
)

# 11: Sprite(4, fd): 08:00:00:00 (8)
house_0_32bpp_png = ImageFile('resources/house_0_32bpp.png')
g.add(
    FileSprite(house_0_32bpp_png, 5, 5, 256, 384, xofs=-128, yofs=-352, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 271, 5, 512, 768, xofs=-256, yofs=-704, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 793, 5, 1024, 1536, xofs=-512, yofs=-1408, zoom=ZOOM_4X),
)

# 12: Sprite(4, fd): 08:00:00:00 (8)
g.add(
    FileSprite(house_0_32bpp_png, 5, 5, 256, 384, xofs=-128, yofs=-352, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 271, 5, 512, 768, xofs=-256, yofs=-704, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 793, 5, 1024, 1536, xofs=-512, yofs=-1408, zoom=ZOOM_4X),
)

# 13: Sprite(4, fd): 08:00:00:00 (8)
g.add(
    FileSprite(house_0_32bpp_png, 5, 5, 256, 384, xofs=-128, yofs=-352, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 271, 5, 512, 768, xofs=-256, yofs=-704, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 793, 5, 1024, 1536, xofs=-512, yofs=-1408, zoom=ZOOM_4X),
)

# 14: Sprite(4, fd): 08:00:00:00 (8)
g.add(
    FileSprite(house_0_32bpp_png, 5, 5, 256, 384, xofs=-128, yofs=-352, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 271, 5, 512, 768, xofs=-256, yofs=-704, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 793, 5, 1024, 1536, xofs=-512, yofs=-1408, zoom=ZOOM_4X),
)

# 15: Sprite(4, fd): 08:00:00:00 (8)
g.add(
    FileSprite(house_0_32bpp_png, 5, 5, 256, 384, xofs=-128, yofs=-352, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 271, 5, 512, 768, xofs=-256, yofs=-704, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 793, 5, 1024, 1536, xofs=-512, yofs=-1408, zoom=ZOOM_4X),
)

# 16: Sprite(4, fd): 08:00:00:00 (8)
g.add(
    FileSprite(house_0_32bpp_png, 5, 5, 256, 384, xofs=-128, yofs=-352, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 271, 5, 512, 768, xofs=-256, yofs=-704, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 793, 5, 1024, 1536, xofs=-512, yofs=-1408, zoom=ZOOM_4X),
)

# 17: Sprite(4, fd): 08:00:00:00 (8)
g.add(
    FileSprite(house_0_32bpp_png, 5, 5, 256, 384, xofs=-128, yofs=-352, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 271, 5, 512, 768, xofs=-256, yofs=-704, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 793, 5, 1024, 1536, xofs=-512, yofs=-1408, zoom=ZOOM_4X),
)

# 18: Sprite(4, fd): 08:00:00:00 (8)
g.add(
    FileSprite(house_0_32bpp_png, 5, 5, 256, 384, xofs=-128, yofs=-352, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 271, 5, 512, 768, xofs=-256, yofs=-704, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 793, 5, 1024, 1536, xofs=-512, yofs=-1408, zoom=ZOOM_4X),
)

# 19: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 20: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 21: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 22: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 23: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 24: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 25: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 26: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 27: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 28: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 29: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 30: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 31: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 32: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 33: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 34: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 35: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 36: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 37: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 38: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 39: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 40: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 41: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 42: Sprite(4, fd): 20:00:00:00 (32)
g.add(
    FileSprite(house_0_32bpp_png, 1827, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_NORMAL),
    FileSprite(house_0_32bpp_png, 1838, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_2X),
    FileSprite(house_0_32bpp_png, 1849, 5, 1, 1, xofs=0, yofs=0, zoom=ZOOM_4X),
)

# 43: Sprite(17, ff) <02>: 02:07:fe:00:54:0f:00:00:00:00:00:80:00:00:10:10:10
ref_254_1 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=254,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=0, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 44: Sprite(17, ff) <02>: 02:07:fd:00:54:0f:00:00:01:00:00:80:00:00:10:10:10
ref_253_1 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=253,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=1, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 45: Sprite(17, ff) <02>: 02:07:fc:00:54:0f:00:00:02:00:00:80:00:00:10:10:10
ref_252_1 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=252,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=2, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 46: Sprite(17, ff) <02>: 02:07:fb:00:54:0f:00:00:03:00:00:80:00:00:10:10:10
ref_251_1 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=251,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=3, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 47: Sprite(17, ff) <02>: 02:07:fa:00:54:0f:00:00:04:00:00:80:00:00:10:10:10
ref_250_1 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=250,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=4, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 48: Sprite(17, ff) <02>: 02:07:f9:00:54:0f:00:00:05:00:00:80:00:00:10:10:10
ref_249_1 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=249,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=5, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 49: Sprite(17, ff) <02>: 02:07:f8:00:54:0f:00:00:06:00:00:80:00:00:10:10:10
ref_248_1 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=248,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=6, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 50: Sprite(17, ff) <02>: 02:07:f7:00:54:0f:00:00:07:00:00:80:00:00:10:10:10
ref_247_1 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=247,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=7, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 51: Sprite(23, ff) <02>: 02:07:ff:80:00:00:08:fe:00:fd:00:fc:00:fb:00:fa:00:f9:00:f8:00:f7:00
ref_255_1 = RandomSwitch(
    feature=HOUSE,
    ref_id=255,
    scope='self',
    count=None,
    triggers=0,
    cmp_all=False,
    lowest_bit=0,
    groups=[ref_254_1, ref_253_1, ref_252_1, ref_251_1, ref_250_1, ref_249_1, ref_248_1, ref_247_1],
)

# 52: Sprite(7, ff) <03>: 03:07:01:81:00:ff:00
Action3(
    feature=HOUSE,
    wagon_override=False,
    ids=[129],
    maps={},
    default=ref_255_1,
)

# 53: Sprite(17, ff) <02>: 02:07:fe:00:54:0f:00:00:08:00:00:80:00:00:10:10:10
ref_254_2 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=254,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=8, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 54: Sprite(17, ff) <02>: 02:07:fd:00:54:0f:00:00:09:00:00:80:00:00:10:10:10
ref_253_2 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=253,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=9, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 55: Sprite(17, ff) <02>: 02:07:fc:00:54:0f:00:00:0a:00:00:80:00:00:10:10:10
ref_252_2 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=252,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=10, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 56: Sprite(17, ff) <02>: 02:07:fb:00:54:0f:00:00:0b:00:00:80:00:00:10:10:10
ref_251_2 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=251,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=11, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 57: Sprite(17, ff) <02>: 02:07:fa:00:54:0f:00:00:0c:00:00:80:00:00:10:10:10
ref_250_2 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=250,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=12, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 58: Sprite(17, ff) <02>: 02:07:f9:00:54:0f:00:00:0d:00:00:80:00:00:10:10:10
ref_249_2 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=249,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=13, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 59: Sprite(17, ff) <02>: 02:07:f8:00:54:0f:00:00:0e:00:00:80:00:00:10:10:10
ref_248_2 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=248,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=14, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 60: Sprite(17, ff) <02>: 02:07:f7:00:54:0f:00:00:0f:00:00:80:00:00:10:10:10
ref_247_2 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=247,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=15, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 61: Sprite(23, ff) <02>: 02:07:ff:80:00:00:08:fe:00:fd:00:fc:00:fb:00:fa:00:f9:00:f8:00:f7:00
ref_255_2 = RandomSwitch(
    feature=HOUSE,
    ref_id=255,
    scope='self',
    count=None,
    triggers=0,
    cmp_all=False,
    lowest_bit=0,
    groups=[ref_254_2, ref_253_2, ref_252_2, ref_251_2, ref_250_2, ref_249_2, ref_248_2, ref_247_2],
)

# 62: Sprite(7, ff) <03>: 03:07:01:82:00:ff:00
Action3(
    feature=HOUSE,
    wagon_override=False,
    ids=[130],
    maps={},
    default=ref_255_2,
)

# 63: Sprite(17, ff) <02>: 02:07:fe:00:54:0f:00:00:10:00:00:80:00:00:10:10:10
ref_254_3 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=254,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=16, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 64: Sprite(17, ff) <02>: 02:07:fd:00:54:0f:00:00:11:00:00:80:00:00:10:10:10
ref_253_3 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=253,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=17, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 65: Sprite(17, ff) <02>: 02:07:fc:00:54:0f:00:00:12:00:00:80:00:00:10:10:10
ref_252_3 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=252,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=18, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 66: Sprite(17, ff) <02>: 02:07:fb:00:54:0f:00:00:13:00:00:80:00:00:10:10:10
ref_251_3 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=251,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=19, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 67: Sprite(17, ff) <02>: 02:07:fa:00:54:0f:00:00:14:00:00:80:00:00:10:10:10
ref_250_3 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=250,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=20, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 68: Sprite(17, ff) <02>: 02:07:f9:00:54:0f:00:00:15:00:00:80:00:00:10:10:10
ref_249_3 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=249,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=21, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 69: Sprite(17, ff) <02>: 02:07:f8:00:54:0f:00:00:16:00:00:80:00:00:10:10:10
ref_248_3 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=248,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=22, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 70: Sprite(17, ff) <02>: 02:07:f7:00:54:0f:00:00:17:00:00:80:00:00:10:10:10
ref_247_3 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=247,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=23, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 71: Sprite(23, ff) <02>: 02:07:ff:80:00:00:08:fe:00:fd:00:fc:00:fb:00:fa:00:f9:00:f8:00:f7:00
ref_255_3 = RandomSwitch(
    feature=HOUSE,
    ref_id=255,
    scope='self',
    count=None,
    triggers=0,
    cmp_all=False,
    lowest_bit=0,
    groups=[ref_254_3, ref_253_3, ref_252_3, ref_251_3, ref_250_3, ref_249_3, ref_248_3, ref_247_3],
)

# 72: Sprite(7, ff) <03>: 03:07:01:83:00:ff:00
Action3(
    feature=HOUSE,
    wagon_override=False,
    ids=[131],
    maps={},
    default=ref_255_3,
)

# 73: Sprite(17, ff) <02>: 02:07:fe:00:54:0f:00:00:18:00:00:80:00:00:10:10:10
ref_254_4 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=254,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=24, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 74: Sprite(17, ff) <02>: 02:07:fd:00:54:0f:00:00:19:00:00:80:00:00:10:10:10
ref_253_4 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=253,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=25, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 75: Sprite(17, ff) <02>: 02:07:fc:00:54:0f:00:00:1a:00:00:80:00:00:10:10:10
ref_252_4 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=252,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=26, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 76: Sprite(17, ff) <02>: 02:07:fb:00:54:0f:00:00:1b:00:00:80:00:00:10:10:10
ref_251_4 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=251,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=27, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 77: Sprite(17, ff) <02>: 02:07:fa:00:54:0f:00:00:1c:00:00:80:00:00:10:10:10
ref_250_4 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=250,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=28, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 78: Sprite(17, ff) <02>: 02:07:f9:00:54:0f:00:00:1d:00:00:80:00:00:10:10:10
ref_249_4 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=249,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=29, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 79: Sprite(17, ff) <02>: 02:07:f8:00:54:0f:00:00:1e:00:00:80:00:00:10:10:10
ref_248_4 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=248,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=30, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 80: Sprite(17, ff) <02>: 02:07:f7:00:54:0f:00:00:1f:00:00:80:00:00:10:10:10
ref_247_4 = BasicSpriteLayout(
    feature=HOUSE,
    ref_id=247,
    ground={'sprite': SpriteRef(id=3924, pal=0, is_global=True, use_recolour=False, always_transparent=False, no_transparent=False)},
    building={'sprite': SpriteRef(id=31, pal=0, is_global=False, use_recolour=False, always_transparent=False, no_transparent=False), 'offset': (0, 0, 0), 'extent': (16, 16, 16)},
)

# 81: Sprite(23, ff) <02>: 02:07:ff:80:00:00:08:fe:00:fd:00:fc:00:fb:00:fa:00:f9:00:f8:00:f7:00
ref_255_4 = RandomSwitch(
    feature=HOUSE,
    ref_id=255,
    scope='self',
    count=None,
    triggers=0,
    cmp_all=False,
    lowest_bit=0,
    groups=[ref_254_4, ref_253_4, ref_252_4, ref_251_4, ref_250_4, ref_249_4, ref_248_4, ref_247_4],
)

# 82: Sprite(7, ff) <03>: 03:07:01:84:00:ff:00
Action3(
    feature=HOUSE,
    wagon_override=False,
    ids=[132],
    maps={},
    default=ref_255_4,
)

# 83: Real sprite(8): (68493, 43): Image house_0: RGBA 256x384 zoom=0 x_offs=-128 y_offs=-352 decomp_size=393216
# 84: Real sprite(8): (273414, 43): Image house_0: RGBA 512x768 zoom=2 x_offs=-256 y_offs=-704 decomp_size=1572864
# 85: Real sprite(8): (1092516, 43): Image house_0: RGBA 1024x1536 zoom=1 x_offs=-512 y_offs=-1408 decomp_size=6291456
# 86: Real sprite(32): (15, 43): Image house_0: RGBA 1x1 zoom=0 x_offs=0 y_offs=0 decomp_size=4
# 87: Real sprite(32): (15, 43): Image house_0: RGBA 1x1 zoom=2 x_offs=0 y_offs=0 decomp_size=4
# 88: Real sprite(32): (15, 43): Image house_0: RGBA 1x1 zoom=1 x_offs=0 y_offs=0 decomp_size=4

g.write('grfpy_building.grf')